name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
 
 # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@latest
        go env -w GO111MODULE=auto
        go get -u github.com/xitongsys/parquet-go-source/local
        go get -u github.com/xitongsys/parquet-go/parquet
        go get -u github.com/xitongsys/parquet-go/writer
        go get -u gopkg.in/ini.v1
        
    - name: Build
      run: go build -v S3qImporterPq.go
 
 # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet S3qImporterPq.go 
        golint S3qImporterPq.go
    
    - name: Test
      run: go test -v S3qImporterPq
